### ISSUE TITLE
grammar problem

### ISSUE THREAD

**Issue by empleished** [empleished/deontobot#24]
Traceback (most recent call last):
  File "parser.py", line 10, in <module>
    rule = parser.prog()
  File "/home/fooleish/humeanator/deontobot/implementation/spec/DeoParser.py", line 102, in prog
    retval.start = self.input.LT(1)
  File "/usr/local/lib/python2.7/dist-packages/antlr3/streams.py", line 801, in LT
    self.fillBuffer()
  File "/usr/local/lib/python2.7/dist-packages/antlr3/streams.py", line 698, in fillBuffer
    t = self.tokenSource.nextToken()
  File "/usr/local/lib/python2.7/dist-packages/antlr3/recognizers.py", line 1117, in nextToken
    self.mTokens()
  File "/home/fooleish/humeanator/deontobot/implementation/spec/DeoLexer.py", line 820, in mTokens
    self.match(EOF)
  File "/usr/local/lib/python2.7/dist-packages/antlr3/recognizers.py", line 1213, in match
    mte = MismatchedTokenException(unichr(s), self.input)
ValueError: unichr() arg not in range(0x110000) (wide Python build)

**Comment by empleished** [comment]
line 1:0 required (...)+ loop did not match anything at input u'term'
